// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAirsoft.Web.Data;

#nullable disable

namespace ProjectAirsoft.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241209134552_SeedGames")]
    partial class SeedGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("184bf0c1-f0c6-41ba-94f4-fc8efcb6d0f9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ccc2090d-2bcb-4c1a-b400-97d2e8bd84c0",
                            Email = "player1@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "PLAYER1@GMAIL.COM",
                            NormalizedUserName = "PLAYER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGN2R3JJWAqlMussiQCPhzn6eIqGw0uEdJDLwt3n/KQWcE186LBrIedMQFZR3Zl7BQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "63a4ec85-5b44-496a-8e68-76f281065d49",
                            TwoFactorEnabled = false,
                            UserName = "player1"
                        },
                        new
                        {
                            Id = new Guid("d2c05c9e-643e-4fd0-9ab4-b01fa657c6b2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43ecbc7c-bf63-43e0-95ac-d4ac58049738",
                            Email = "player2@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "PLAYER2@GMAIL.COM",
                            NormalizedUserName = "PLAYER2",
                            PasswordHash = "AQAAAAIAAYagAAAAECqE9lfs7UmPH9XH1qughf9MWlj1zgVL3CGPY7HHYlZfDrVqCsEIJY0MMCPRqIi+VA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7633da9-e5a8-45e1-b1b7-800956ffb8e2",
                            TwoFactorEnabled = false,
                            UserName = "player2"
                        },
                        new
                        {
                            Id = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a10e574-819b-440e-8bac-c19f74b5d1d6",
                            Email = "manager@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "MANAGER@GMAIL.COM",
                            NormalizedUserName = "MANAGER",
                            PasswordHash = "AQAAAAIAAYagAAAAEHxmIFLB5l6cCv7n8YL7XdbFenMXRz3NVJOgXqhEgWnKRA41Sj0wvl77blXmEnpkpQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e31d4129-ac8a-41f5-ba9c-0c215a2809bb",
                            TwoFactorEnabled = false,
                            UserName = "manager"
                        });
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The city identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("The name of the city");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Plovdiv"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Varna"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Burgas"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ruse"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Stara Zagora"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pleven"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sliven"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dobrich"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Shumen"
                        });
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The comment identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The author identifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("The content of the comment");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The date and time when the comment is created");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The game identifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GameId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The game identifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("The maximum number of players");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date when the game will be held");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("The description of the game");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The one-time fee that players have to pay");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The image URL of the game");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit")
                        .HasComment("Flag for canceled games");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Flag for soft delete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasComment("The name of the game");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The organizer identifier");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("The time when the game will start");

                    b.Property<Guid>("TerrainId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The terrain identifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("TerrainId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e83cba8-74e2-4552-9a3c-0d216016a688"),
                            Capacity = 80,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for an adrenaline-fueled day of tactical gameplay as two teams clash in an epic Team Deathmatch! This fast-paced, high-stakes airsoft event is designed to test your strategy, teamwork, and shooting skills in an exciting outdoor arena. Game Rules and Format: Players will be divided into two teams. Each team starts from its designated base. The objective is simple: eliminate as many opponents as possible while minimizing your team’s losses. The team with the most eliminations by the end of the game wins! When a player is hit, they are considered \"eliminated\" and must immediately return to their team’s base. Eliminated players have a 10-minute respawn timer. Once the timer is up, they may re-enter the battlefield, ready to rejoin the action. Communication, coordination, and tactics are key to gaining the upper hand and dominating the opposition. Safety Guidelines: All players must wear proper protective gear, including face masks and goggles, at all times. Only approved airsoft replicas are permitted on the field, and all weapons must be chrono-tested before the event. Maintain sportsmanship and adhere to the honor system—call your hits!",
                            Fee = 2.00m,
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Sunday Game #1",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "10:00",
                            TerrainId = new Guid("63b8246a-aa5c-4964-95c9-10d42eb07b65")
                        },
                        new
                        {
                            Id = new Guid("87536500-af29-4d83-afa8-17ba088f6be8"),
                            Capacity = 120,
                            Date = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get ready for an exhilarating day of strategy and action with a classic Capture the Flag airsoft showdown! Two teams will battle it out in a thrilling test of teamwork, tactics, and speed, all set in an immersive battlefield environment. Game Rules and Format: Teams will start at their respective bases, each guarding their own flag while strategizing to capture the opponent’s. The objective is to successfully retrieve the enemy flag from their base and return it to your own while defending your flag from capture. Players hit during gameplay must return to their base and wait for a 5-minute respawn timer before rejoining the action. Communication and coordination are essential for both offense and defense. Work together to outsmart and outmaneuver your opponents! A successful flag capture earns your team a point, and the team with the most points at the end of the game wins. Safety Guidelines: All players must wear approved protective gear, including face masks and goggles, throughout the event. Only field-approved airsoft replicas are allowed, and all weapons will be chrono-tested for safety. Honor the game and your opponents—call your hits and maintain sportsmanship at all times.",
                            Fee = 0m,
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Sunday Game #2",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "11:30",
                            TerrainId = new Guid("a8177ba1-f5af-4ec4-8631-41a1a5250460")
                        },
                        new
                        {
                            Id = new Guid("4f6d481d-b666-4a2e-83f0-4aec22accdf8"),
                            Capacity = 200,
                            Date = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Step into the ultimate battlefield for a day of intense competition in Battle Stations Domination! Two teams will go head-to-head, fighting to capture and hold key objectives while racking up points in this high-energy, strategy-driven airsoft game. Game Rules and Format: The terrain is equipped with 3 Battle Stations, each serving as a critical control point. Your mission: capture these stations and hold them for as long as possible. Every second a Battle Station is under your team’s control, it generates points. To capture a station, your team must secure the area and raise your team’s flag or activate the station marker. The station will remain yours until the opposing team takes it back. Eliminated players must return to their team’s base and wait for a 5-minute respawn timer before returning to the action. The team with the highest total points at the end of the game claims victory! Strategy Tips: Coordinate your team to attack, defend, and rotate positions. Balancing offense and defense is key to dominating the field. Use communication and tactics to outmaneuver your opponents and seize the advantage. Prioritize teamwork—every player’s role contributes to overall success! Safety Guidelines: All players must wear approved protective gear, including face masks and goggles. Only field-approved airsoft replicas are allowed, and all weapons must pass a chrono test before the game. Call your hits and maintain sportsmanship throughout the event.",
                            Fee = 5.00m,
                            ImageUrl = "https://www.surplusstore.co.uk/wp/wp-content/uploads/sites/1/2018/07/800px-US_Navy_SEAL_Reenactment_Group.jpg",
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Battle Stations",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "09:30",
                            TerrainId = new Guid("01ac2f70-21e0-417f-b18a-41c9aa1055b6")
                        },
                        new
                        {
                            Id = new Guid("17f7524e-ce89-4e78-aa9f-41f440f3466b"),
                            Capacity = 150,
                            Date = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gear up for an action-packed airsoft experience in VIP Rescue Mission, where strategy, precision, and teamwork are essential for success! In this high-stakes scenario, one team must escort a designated VIP to safety, while the opposing team does everything they can to capture or eliminate the target. Game Rules and Format: The VIP starts with the Defender Team at their base and must be safely escorted to a designated extraction point on the field. The Attacker Team’s mission is to intercept the VIP and prevent their extraction by capturing or eliminating them. The VIP is unarmed but equipped with a small shield for limited protection. Defenders must work as a unit to protect the VIP, while attackers use strategy and firepower to block their progress. If the VIP reaches the extraction point unharmed, the Defenders win. If the VIP is eliminated or captured, the Attackers win. Special Rules for the VIP: The VIP cannot run or hide without their team’s protection and must always remain visible during the game. If the VIP is hit, they are “down” but not eliminated and must remain stationary until they are “rescued” by a Defender within 2 minutes. If no rescue occurs, the game ends with an Attacker victory.",
                            Fee = 2.00m,
                            ImageUrl = "https://adeptairsoft.com/wp-content/uploads/2024/02/join-airsoft-team.png",
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "VIP Rescue",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "12:00",
                            TerrainId = new Guid("8b031c23-6687-4338-9845-5e9af3af951c")
                        },
                        new
                        {
                            Id = new Guid("1948672c-706d-474f-b4b0-5c1f9cf6f440"),
                            Capacity = 60,
                            Date = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for a thrilling and immersive experience under the cover of darkness with Night Ops! This after-hours airsoft game takes the action to a whole new level, where strategy and stealth are key to survival. The battlefield transforms into a realm of suspense and tactical maneuvers, pushing your skills to their limits. Game Format: Teams will engage in a series of nighttime missions, ranging from strategic objectives like capturing control points to intense combat scenarios. Visibility is limited, so players must rely on teamwork, communication, and tactical use of flashlights and night vision (if available). Silent eliminations and ambush tactics will be game-changers in this nocturnal showdown. Nighttime Rules and Safety: Light Discipline: Flashlights and other illumination tools must be used sparingly to avoid giving away positions. Glow sticks or reflective markers will identify teammates. Safety First: All players must wear standard protective gear, including goggles and face masks, with additional reflective markers to ensure visibility during gameplay. Be extra cautious when moving in the dark terrain to avoid trips or falls. Equipment Tips: Bring flashlights, headlamps, or mounted tactical lights for your replicas. Wear dark or camouflaged clothing suitable for nighttime play. Glow sticks or colored armbands will be provided for team identification.",
                            Fee = 0m,
                            ImageUrl = "https://www.redwolfairsoft.com/wp/wp-content/uploads/2020/12/team-1024x784.jpg",
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Night Ops",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "20:00",
                            TerrainId = new Guid("c48effd1-f1a7-4c8b-a60a-7cd7c626d49a")
                        },
                        new
                        {
                            Id = new Guid("d837bea0-00d5-4067-89c4-3b05c55dcfdf"),
                            Capacity = 100,
                            Date = new DateTime(2024, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get ready for an intense airsoft showdown in Capture the Flag, where teamwork, strategy, and precision are the keys to victory! Two rival teams will face off in a high-energy competition to seize the enemy’s flag while defending their own in a dynamic battlefield. Game Rules and Format: Each team starts at their base with their flag securely placed. The objective is simple yet challenging: infiltrate the enemy base, capture their flag, and return it to your base without being eliminated. If a player is hit, they are eliminated and must return to their base for a 5-minute respawn timer before re-entering the game. A successful flag capture earns your team a point, but the game doesn't end there—multiple captures can be achieved within the game time limit. The team with the most points at the end of the game wins. Strategy Tips: Balance offense and defense by assigning players to attack, defend, and scout. Communication is crucial—coordinate your movements and adapt to the enemy’s strategy. Be quick and precise in your movements; the faster you capture the flag, the better your chances of outscoring the opponent! Safety Guidelines: Protective gear, including goggles and face masks, is mandatory for all players. Only field-approved airsoft replicas are permitted, and all weapons must pass a chrono test before gameplay. Adhere to the honor system—call your hits and respect the game.",
                            Fee = 5.00m,
                            ImageUrl = "https://www.defconairsoft.co.uk/wp-content/uploads/2024/02/capture-the-plag.png",
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Capture the Flag",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "10:00",
                            TerrainId = new Guid("a8177ba1-f5af-4ec4-8631-41a1a5250460")
                        },
                        new
                        {
                            Id = new Guid("a3ccaad2-3c92-4e93-9ce0-ab122ea65668"),
                            Capacity = 200,
                            Date = new DateTime(2024, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for a heart-pounding airsoft experience in Domination, where tactical mastery and team coordination are the keys to victory! Two teams will battle for control of multiple zones across the battlefield, with every second of domination earning critical points. Game Rules and Format: The battlefield features 3 strategic zones that serve as control points. Each zone can be claimed by raising your team’s flag or activating the zone marker. Your objective: capture and hold as many zones as possible for as long as you can. Every second a zone is under your team’s control earns points. If a player is hit, they are eliminated and must return to their base for a 5-minute respawn timer before returning to the field. The team with the most points at the end of the game wins. Strategy Tips: Balance your forces between offense, defense, and zone rotation to maximize your team’s dominance. Communication and quick decision-making are vital—adapt to the enemy’s movements and focus on holding key zones. Remember, controlling multiple zones increases your score rate, so think strategically about where to focus your efforts. Safety Guidelines: All players must wear approved protective gear, including face masks and goggles, at all times. All airsoft replicas must pass a chrono test before the game begins. Play fair and honor the rules—call your hits and respect your fellow players.",
                            Fee = 10.00m,
                            ImageUrl = "https://i.servimg.com/u/f58/19/63/04/66/tm/dsc00025.jpg",
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Domination",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "11:00",
                            TerrainId = new Guid("838d3b35-4413-4721-870e-32b00bde5f8e")
                        },
                        new
                        {
                            Id = new Guid("7ccfa9fc-ff63-42cf-ba59-30584cb0a206"),
                            Capacity = 500,
                            Date = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join the battle in Border War, a dynamic and high-stakes airsoft scenario where two teams clash over contested territory along a shifting frontline. This intense game mode challenges players to adapt, strategize, and work as a unit to claim victory. Game Rules and Format: The battlefield is divided into several zones along a central border, representing a contested area. Teams start at their respective bases and must advance to capture and control zones along the border. To claim a zone, your team must eliminate all opponents in the area and raise your flag or activate the zone marker. The frontline shifts as zones are captured, with both teams pushing to expand their territory. Each controlled zone generates points for your team every minute. The team with the most points at the end of the game wins. Eliminated players must return to their base for a 5-minute respawn timer before rejoining the battle. Strategy Tips: Coordinate your team to maintain a strong presence at captured zones while continuing to push the enemy back. Use scouting and flanking tactics to outmaneuver your opponents and surprise them in contested areas. Communication is critical—adapt your strategy as the frontline shifts and new zones come into play.",
                            Fee = 50.00m,
                            ImageUrl = "https://airsoft-info.at/wp-content/uploads/2023/09/borderwar.jpg",
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Border War",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "14:00",
                            TerrainId = new Guid("c48effd1-f1a7-4c8b-a60a-7cd7c626d49a")
                        },
                        new
                        {
                            Id = new Guid("efd6ab61-0ec5-498c-ba80-61bb1dfb660c"),
                            Capacity = 80,
                            Date = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for an adrenaline-fueled day of tactical gameplay as two teams clash in an epic Team Deathmatch! This fast-paced, high-stakes airsoft event is designed to test your strategy, teamwork, and shooting skills in an exciting outdoor arena. Game Rules and Format: Players will be divided into two teams. Each team starts from its designated base. The objective is simple: eliminate as many opponents as possible while minimizing your team’s losses. The team with the most eliminations by the end of the game wins! When a player is hit, they are considered \"eliminated\" and must immediately return to their team’s base. Eliminated players have a 10-minute respawn timer. Once the timer is up, they may re-enter the battlefield, ready to rejoin the action. Communication, coordination, and tactics are key to gaining the upper hand and dominating the opposition. Safety Guidelines: All players must wear proper protective gear, including face masks and goggles, at all times. Only approved airsoft replicas are permitted on the field, and all weapons must be chrono-tested before the event. Maintain sportsmanship and adhere to the honor system—call your hits!",
                            Fee = 2.00m,
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Sunday Game #3",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "10:00",
                            TerrainId = new Guid("01ac2f70-21e0-417f-b18a-41c9aa1055b6")
                        },
                        new
                        {
                            Id = new Guid("c0a3e339-d04a-41e1-8b8c-cff9b8b96149"),
                            Capacity = 80,
                            Date = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for an adrenaline-fueled day of tactical gameplay as two teams clash in an epic Team Deathmatch! This fast-paced, high-stakes airsoft event is designed to test your strategy, teamwork, and shooting skills in an exciting outdoor arena. Game Rules and Format: Players will be divided into two teams. Each team starts from its designated base. The objective is simple: eliminate as many opponents as possible while minimizing your team’s losses. The team with the most eliminations by the end of the game wins! When a player is hit, they are considered \"eliminated\" and must immediately return to their team’s base. Eliminated players have a 10-minute respawn timer. Once the timer is up, they may re-enter the battlefield, ready to rejoin the action. Communication, coordination, and tactics are key to gaining the upper hand and dominating the opposition. Safety Guidelines: All players must wear proper protective gear, including face masks and goggles, at all times. Only approved airsoft replicas are permitted on the field, and all weapons must be chrono-tested before the event. Maintain sportsmanship and adhere to the honor system—call your hits!",
                            Fee = 2.00m,
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Sunday Game #4",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "10:00",
                            TerrainId = new Guid("01ac2f70-21e0-417f-b18a-41c9aa1055b6")
                        },
                        new
                        {
                            Id = new Guid("07d6ad43-126f-4906-bed8-80ee555fbe26"),
                            Capacity = 80,
                            Date = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for an adrenaline-fueled day of tactical gameplay as two teams clash in an epic Team Deathmatch! This fast-paced, high-stakes airsoft event is designed to test your strategy, teamwork, and shooting skills in an exciting outdoor arena. Game Rules and Format: Players will be divided into two teams. Each team starts from its designated base. The objective is simple: eliminate as many opponents as possible while minimizing your team’s losses. The team with the most eliminations by the end of the game wins! When a player is hit, they are considered \"eliminated\" and must immediately return to their team’s base. Eliminated players have a 10-minute respawn timer. Once the timer is up, they may re-enter the battlefield, ready to rejoin the action. Communication, coordination, and tactics are key to gaining the upper hand and dominating the opposition. Safety Guidelines: All players must wear proper protective gear, including face masks and goggles, at all times. Only approved airsoft replicas are permitted on the field, and all weapons must be chrono-tested before the event. Maintain sportsmanship and adhere to the honor system—call your hits!",
                            Fee = 2.00m,
                            IsCanceled = false,
                            IsDeleted = false,
                            Name = "Sunday Game #5",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "10:00",
                            TerrainId = new Guid("01ac2f70-21e0-417f-b18a-41c9aa1055b6")
                        },
                        new
                        {
                            Id = new Guid("9bf8c44b-651c-4141-8c07-52572a01b4a8"),
                            Capacity = 80,
                            Date = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for an adrenaline-fueled day of tactical gameplay as two teams clash in an epic Team Deathmatch! This fast-paced, high-stakes airsoft event is designed to test your strategy, teamwork, and shooting skills in an exciting outdoor arena. Game Rules and Format: Players will be divided into two teams. Each team starts from its designated base. The objective is simple: eliminate as many opponents as possible while minimizing your team’s losses. The team with the most eliminations by the end of the game wins! When a player is hit, they are considered \"eliminated\" and must immediately return to their team’s base. Eliminated players have a 10-minute respawn timer. Once the timer is up, they may re-enter the battlefield, ready to rejoin the action. Communication, coordination, and tactics are key to gaining the upper hand and dominating the opposition. Safety Guidelines: All players must wear proper protective gear, including face masks and goggles, at all times. Only approved airsoft replicas are permitted on the field, and all weapons must be chrono-tested before the event. Maintain sportsmanship and adhere to the honor system—call your hits!",
                            Fee = 2.00m,
                            IsCanceled = true,
                            IsDeleted = false,
                            Name = "Sunday Game #6",
                            OrganizerId = new Guid("0e773424-25ab-4d83-a5c9-a5f3665ef336"),
                            StartTime = "10:00",
                            TerrainId = new Guid("01ac2f70-21e0-417f-b18a-41c9aa1055b6")
                        });
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The team identifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasComment("The city identifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The leader identifier");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The logo URL of the game");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasComment("The name of the team");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("LeaderId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Terrain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The terrain identifier");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasComment("The city identifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Flag for active/inactive terrain");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Flag for soft delete");

                    b.Property<string>("LocationUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("The URL of the location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The name of the terrain");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Terrains");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63b8246a-aa5c-4964-95c9-10d42eb07b65"),
                            CityId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            LocationUrl = "https://maps.app.goo.gl/5ZFey2vRCUqduQZ48",
                            Name = "Antifreeze"
                        },
                        new
                        {
                            Id = new Guid("8b031c23-6687-4338-9845-5e9af3af951c"),
                            CityId = 3,
                            IsActive = true,
                            IsDeleted = false,
                            LocationUrl = "https://maps.app.goo.gl/f3MciMAqqMgjKzNd9",
                            Name = "Horse Base"
                        },
                        new
                        {
                            Id = new Guid("01ac2f70-21e0-417f-b18a-41c9aa1055b6"),
                            CityId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            LocationUrl = "https://maps.app.goo.gl/Uyhob7UD8pahXxXy5",
                            Name = "Green Water"
                        },
                        new
                        {
                            Id = new Guid("838d3b35-4413-4721-870e-32b00bde5f8e"),
                            CityId = 10,
                            IsActive = true,
                            IsDeleted = false,
                            LocationUrl = "https://maps.app.goo.gl/epw8PCoW2TsQamtF7",
                            Name = "Residence"
                        },
                        new
                        {
                            Id = new Guid("a8177ba1-f5af-4ec4-8631-41a1a5250460"),
                            CityId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            LocationUrl = "https://maps.app.goo.gl/Q8E4aBXsvyYjyzRj6",
                            Name = "Airsoft Sofia Field"
                        },
                        new
                        {
                            Id = new Guid("c48effd1-f1a7-4c8b-a60a-7cd7c626d49a"),
                            CityId = 1,
                            IsActive = true,
                            IsDeleted = false,
                            LocationUrl = "https://maps.app.goo.gl/qzZ24mimwva19fff7",
                            Name = "BoinoPole"
                        });
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.UserGame", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user identifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The game identifier");

                    b.HasKey("UserId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UsersGames");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.Team", null)
                        .WithMany("Members")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Comment", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAirsoft.Data.Models.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Game", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAirsoft.Data.Models.Terrain", "Terrain")
                        .WithMany("Games")
                        .HasForeignKey("TerrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Terrain");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Team", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.City", "City")
                        .WithMany("Teams")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Terrain", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.City", "City")
                        .WithMany("Terrains")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.UserGame", b =>
                {
                    b.HasOne("ProjectAirsoft.Data.Models.Game", "Game")
                        .WithMany("UsersGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAirsoft.Data.Models.ApplicationUser", "User")
                        .WithMany("UsersGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UsersGames");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.City", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Terrains");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Game", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UsersGames");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ProjectAirsoft.Data.Models.Terrain", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
